# -*- coding: utf-8 -*-
"""ev_charging_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K94KAcOMGYMMN4h3UIKXfMoGBfI7kqSc
"""

!pip install pandas numpy matplotlib scikit-learn

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import IsolationForest
from sklearn.metrics import mean_absolute_error

# Firebase Realtime Database URL
url = "https://ev-wireless-charging-ae877-default-rtdb.firebaseio.com/EV_001.json"

response = requests.get(url)
json_data = response.json()

# Safety check
if json_data is None or len(json_data) == 0:
    raise ValueError("Firebase dataset is empty. Power ON ESP32 and try again.")

# Convert Firebase JSON → DataFrame
data = pd.DataFrame.from_dict(json_data, orient="index")

# Reset index for cleanliness
data.reset_index(drop=True, inplace=True)

data.head()

# Convert required columns to numeric
cols = ["current", "power", "energy", "charging", "fault"]
data[cols] = data[cols].apply(pd.to_numeric, errors="coerce")

# Remove invalid rows
data = data.dropna(subset=["current", "power", "energy"])

# keep rows where power is valid
#data = data[data["power"] >= 0]

print("Rows remaining:", len(data))

data.head()

battery_capacity_Wh = 10  # assumed capacity

data["Time_Remaining_hr"] = np.where(
    data["power"] > 0,
    (battery_capacity_Wh - data["energy"]) / data["power"],
    np.nan
)
if len(data) < 5:
    raise ValueError("Not enough EV charging data. Run ESP32 longer to collect data.")
X = data[["current", "power", "energy"]]
y = data["Time_Remaining_hr"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model_time = LinearRegression()
model_time.fit(X_train, y_train)

pred = model_time.predict(X_test)
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, pred))

features = data[["current", "power"]]

anomaly_model = IsolationForest(
    contamination=0.05, random_state=42
)
data["Anomaly"] = anomaly_model.fit_predict(features)

data["Anomaly"].value_counts()

plt.figure(figsize=(6,4))
plt.scatter(
    data["power"],
    data["current"],
    c=data["Anomaly"],
    cmap="coolwarm"
)
plt.xlabel("Power (W)")
plt.ylabel("Current (A)")
plt.title("Anomaly Detection in EV Charging")
plt.colorbar(label="Anomaly")
plt.show()

data["Efficiency (%)"] = (
    data["energy"] / battery_capacity_Wh
) * 100

plt.figure(figsize=(6,4))
plt.plot(data["Efficiency (%)"], color="green")
plt.xlabel("Time Index")
plt.ylabel("Efficiency (%)")
plt.title("Charging Efficiency Over Time")
plt.show()

data["Predicted_Fault"] = (
    (data["Anomaly"] == -1) |
    (data["fault"] == 1)
).astype(int)

data["Predicted_Fault"].value_counts()

data.to_csv("EV_Charging_ML_Output.csv", index=False)
print("ML Output Dataset Saved Successfully")

plt.plot(data["current"])
plt.xlabel("Time Index")
plt.ylabel("Current (A)")
plt.title("Current vs Time")
plt.show()

plt.plot(data["energy"], color="green")
plt.xlabel("Time Index")
plt.ylabel("Energy (Wh)")
plt.title("Energy Accumulation Over Time")
plt.show()

plt.scatter(
    data["power"],
    data["current"],
    c=data["Anomaly"],
    cmap="coolwarm"
)
plt.xlabel("Power (W)")
plt.ylabel("Current (A)")
plt.title("Anomaly Detection in Charging")
plt.show()

plt.plot(data["Efficiency (%)"], color="purple")
plt.xlabel("Time Index")
plt.ylabel("Efficiency (%)")
plt.title("Charging Efficiency Trend")
plt.show()